raw_data_path: "data/processed/egyptian_civil_code.json"
processed_data_path: "data/processed/chunks_article_aware.json"


embedding_model: "BAAI/bge-m3"

qdrant:
  path: "./qdrant_storage"
  collection_name: "egyptian_civil_code"

retriever:
  top_k: 7

mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "egyptian-legal-rag-project2"

generator:
  model_name: "openai/gpt-oss-120b" 
  temperature: 0.0
  max_tokens: 2048
